namespace OrixNotch.Shell;

/// <summary>
/// App-wide icon vocabulary, rendered by <see cref="HeroIcon"/> from vendored
/// Heroicons artwork (MIT, tailwindlabs/heroicons). One member per glyph; the
/// solid/outline choice is made by <see cref="HeroIcon"/> (see
/// <see cref="HeroVariant"/>), so call sites only name the icon.
/// </summary>
public enum AppIcon
{
    Grid,
    Sparkles,
    ChartBar,
    ArchiveBox,
    ClipboardList,
    DocText,
    Stack,
    MusicNote,
    BookOpen,
    ListBullet,
    Clock,
    CalendarDays,
    Cloud,
    Signal,
    ChartLine,
    ArrowsLeftRight,
    FaceSmile,
    Play,
    Pause,
    Plus,
    XMark,
    Trash,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronDown,
    ChevronUpDown,
    Ellipsis,
    Check,
    Magnifier,
    MapPin,
    Link,
    Photo,
    Folder,
    File,
    Pin,
    PinSlash,
    Gear,
    Info,
    Adjust,
    Palette,
    Monitor,
    Terminal,
    Keyboard,
    Teleprompter,
    Stop,
    Refresh,
    Pencil,
    Star,
    Copy,
    Cpu,
    Memory,
    Drive,
    Wifi,
    ArrowUp,
    ArrowDown,
    ArrowRight,
    ArrowsUpDown,
    Bolt,
    Moon,
    Rocket,
    Language,
    Sun,
    LightBulb,
    Quote,
    Fire,
    Drop,
    Cake,
    Globe,
    Map,
    Flag,
    Trophy,
    Heart,
    User,
    Backward,
    Forward,
    BatteryFull,
}
